name: build

on:
  push:
   tags:
     - "*"

jobs:
  release-osx:
    runs-on: macos-latest    
    steps:
    - uses: actions/checkout@v2

    - name: Get Version
      id: version
      run: |
        SAP_VERSION=$(cat resources/VERSION)
        echo "##[set-output name=version;]${SAP_VERSION}"

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'tar'
        filename: 'sap-${{ steps.version.outputs.version }}-macos.tar.gz'
        exclusions: '*.git* README.md resources'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "sap-${{ steps.version.outputs.version }}-macos.tar.gz"
        bodyFile: "resources/release-notes/v${{ steps.version.outputs.version }}.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true

    - name: Bump homebrew-tap formula
      uses: mislav/bump-homebrew-formula-action@v1
      env:
        COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
      with:
        formula-name: sap
        formula-path: sap.rb
        homebrew-tap: wanishing/homebrew-sap
        download-url: "https://github.com/wanishing/sap/releases/download/v${{ steps.version.outputs.version }}/sap-${{ steps.version.outputs.version }}-macos.tar.gz"




